config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get "/", to: "application#homepage", as: "homepage"
  
  resources :devs
  resources :projects
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dev.rb
class Dev < ApplicationRecord
    has_many :dev_projects
    has_many :projects, through: :dev_projects


    def self.company(company_name)
        Dev.where(workplace: company_name)
    end
end

app/models/dev_project.rb
class DevProject < ApplicationRecord
    belongs_to :dev
    belongs_to :project
end

app/models/project.rb
class Project < ApplicationRecord
    has_many :dev_projects
    has_many :devs, through: :dev_projects

   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def homepage
        render :homepage
    end
end

app/controllers/devs_controller.rb
class DevsController < ApplicationController

    before_action :find_dev, only: [:show, :edit, :update, :destroy]

    def index
        if params["company_name"] == "Flat co"
            @devs = Dev.company("Flat co")
            @flat_co = "checked"
            @co = nil
            @all_dev = nil
        elsif params["company_name"] == "Co"
            @devs = Dev.company("Co")
            @flat_co = nil
            @co = "checked"
            @all_dev = nil
        else
            @devs = Dev.all
            @flat_co = nil
            @co = nil
            @all_dev = "checked"
        end
    end

    def show
        # @dev = Dev.find(params[:id])
    end

    def new
        @dev = Dev.new
    end
  
    def create
        @dev = Dev.create(dev_params)
        redirect_to dev_path(@dev)
    end

    def edit
        # @dev = Dev.find(params[:id])
    end

    def update
        # @dev = Dev.find(params[:id])
        @dev.update(dev_params)
        redirect_to dev_path(@dev)
    end

    def destroy
        # @dev = Dev.find(params[:id])
        @dev.destroy
        redirect_to devs_path
    end

    private
    def dev_params
        params.require(:dev).permit(:name, :experience, :workplace, :project_ids => [])
    end

    def find_dev
        @dev = Dev.find(params[:id])
    end
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  def index
    @projects = Project.all
  end

  def show
    find_project
  end
  
  def new
    @project = Project.new
  end

  def create
    @project = Project.create(project_params)
    redirect_to project_path(@project)
  end

  def edit
    find_project
  end

  def update
    find_project
    @project.update(project_params)
    redirect_to project_path(@project)
  end

  def destroy
    find_project
    @project.destroy
    redirect_to projects_path
  end


  private

  def project_params
    params.require(:project).permit(:name, :description, :dev_ids => [])
  end

  def find_project
    @project = Project.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/devs_helper.rb
module DevsHelper
end

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/application/homepage.html.erb
<p> Welcome to Flat CO. Here at Flat Co. we hire all Flatiron grads. The class we started with was the best cohort "2 commit 2 git"</p>

app/views/devs/edit.html.erb
<h1>Edit <%= @dev.name %></h1>

<%= form_for @dev do |f| %>
<%= f.label :name, "Dev Name: " %>
<%= f.text_field :name %>
<%= f.label :experience, "Years of experience: " %>
<%= f.number_field :experience, min: 0, step: 1 %>
<%= f.label :workplace, "Workplace: "%>
<%= f.text_field :workplace %><br><br>
<%=f.label :project_id, "Project selection:"%>
<%= f.collection_check_boxes(:project_ids, Project.all, :id, :name) %>
<%= f.submit %>



<%end %>

app/views/devs/index.html.erb
<div class = "dev_list">
    <h1>Devs list</h1>
    <%= form_tag devs_path, method: "GET" do %>
        <%= radio_button_tag "company_name", "Flat co", checked=@flat_co %>
        <%= label_tag "Works at Flat co" %>
        <%= radio_button_tag "company_name", "Co", checked = @co %>
        <%= label_tag "Works at Co" %>
        <%= radio_button_tag "company_name", "all", checked = @all_dev%>
        <%= label_tag "all" %>
        <%= submit_tag "Submit"%>
    <% end %>
    <ul>
        <% @devs.each do |dev| %>
        <div class ="homepage-devs">
        <li><%= link_to dev.name, dev_path(dev) %></li>
        </div>
        <% end %>
    </ul>

    <h2><%= link_to "Hire a Dev", new_dev_path %></h2>
</div>

app/views/devs/new.html.erb
<h1> Dev new</h1>

<%= form_for @dev do |f| %>
<%= f.label :name, "Dev Name: " %>
<%= f.text_field :name %>
<%= f.label :experience, "Years of experience: " %>
<%= f.number_field :experience, min: 0, step: 1 %>
<%= f.label :workplace, "Workplace: "%>
<%= f.text_field :workplace %><br><br>
<%=f.label :project_id, "Project selection:"%>
<div class="container">
<%= f.collection_check_boxes(:project_ids, Project.all, :id, :name) %>
</div>
<%= f.submit %>



<%end %>

app/views/devs/show.html.erb
<h1><%= @dev.name %></h1>
<label> Work place: <%= @dev.workplace %></label><br>
<label> Years of experience: <%= @dev.experience %></label><br>
<label> Projects: </label>
<% if @dev.projects  %>
<ul>
<% @dev.projects.each do |project| %>
  <li><%= link_to project.name, project_path(project) %></li> 
<%end%>
</ul>
<%end%>

<%= link_to "Edit this Dev", edit_dev_path(@dev)%><br>
<%= link_to "List of devs", devs_path %><br>
<%= link_to "Fire this Dev", dev_path(@dev.id), method: "DELETE"%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Flatco</title>
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <div class ="topnav">
        <%= link_to "FlatCo.", homepage_path %>
        <%= link_to "Dev list", devs_path %>
        <%= link_to "Project list", projects_path %>
      </div>
    </header>
    <%= yield %>
  </body>
</html>

app/views/projects/_project_form.html.erb
<%= form_for @project do |f| %>
<%= f.label :name, "Project Name:" %>
<%= f.text_field :name %><br>
<%= f.label :description, "Project Description:" %><br>
<%= f.text_area :description %><br>
<%= f.label :dev_id, "Devs on Project:" %><br>
<%= f.collection_check_boxes(:dev_ids, Dev.all, :id, :name) %><br>
<%= f.submit %>
<% end %>

app/views/projects/edit.html.erb
<h1>Edit <%= @project.name %></h1>



<%= render partial: "project_form" %>

app/views/projects/index.html.erb
<div class = "project_list"> 
    <h1>Project list</h1>
    <ul>
        <% @projects.each do |project| %>
        <li><%= link_to project.name, project_path(project) %></li>
        <% end %>
    </ul>

    <h2><%= link_to "New Project", new_project_path %></h2>
</div>

app/views/projects/new.html.erb
<h1>New Project</h1>  
<%= render partial: "project_form" %>

app/views/projects/show.html.erb
<h1><%= @project.name %></h1>
<label>Description: </label>
<p><%= @project.description%></p>
<ul>
    <% @project.devs.each do |dev| %>
    <li><%= link_to dev.name, dev_path(dev) %></li>
    <% end %>
</ul>


<%= link_to "Remove project", project_path(@project), method: "DELETE" %><br>
<%= link_to "Project list.", projects_path %>